# Generated by Django 4.1.1 on 2022-09-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('thumnail', models.ImageField(upload_to='thumnail/')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
