# Generated by Django 4.1.1 on 2022-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0002_aboutus_content1_aboutus_content2_aboutus_para_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='para1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='para2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
