# Generated by Django 4.1.1 on 2022-09-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0003_aboutus_para1_aboutus_para2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='course_head',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='course_para',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
