# Generated by Django 4.1.1 on 2022-09-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0005_aboutus_course_list_aboutus_course_list1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='App_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='App_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
