# Generated by Django 4.1.1 on 2022-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0006_aboutus_app_head_aboutus_app_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Acc_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Acc_image',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Acc_image1',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Acc_image2',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Acc_image3',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Acc_image4',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
    ]
