# Generated by Django 4.1.1 on 2022-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0007_aboutus_acc_head_aboutus_acc_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Frequently_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
