# Generated by Django 4.1.1 on 2022-09-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0008_aboutus_frequently_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='choice_para',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='choice_para1',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='choice_para2',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='choice_para3',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
