# Generated by Django 4.1.1 on 2022-09-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0009_aboutus_choice_para_aboutus_choice_para1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='best_para',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para1',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para10',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para11',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para12',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para13',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para14',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para15',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para16',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para17',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para2',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para3',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para4',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para5',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para6',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para7',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para8',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='best_para9',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
