# Generated by Django 4.1.1 on 2022-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0010_aboutus_best_para_aboutus_best_para1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='INC_para',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='INC_para1',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
