# Generated by Django 4.1.1 on 2022-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0013_aboutus_rank_para_aboutus_rank_para1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='rank_para2',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='rank_para3',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='rank_para4',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='rank_para5',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
