# Generated by Django 4.1.1 on 2022-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0017_aboutus_colleges_para_aboutus_colleges_para1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='colleges_para9',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
