# Generated by Django 4.1.1 on 2022-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0018_aboutus_colleges_para9'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Gui_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Gui_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
