# Generated by Django 4.1.1 on 2022-09-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0021_aboutus_banner_img_aboutus_banner_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='logo_img',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
    ]
