# Generated by Django 4.1.1 on 2022-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0023_aboutus_foot_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='foot_cont',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
