# Generated by Django 4.1.1 on 2022-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0024_aboutus_foot_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='copy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='ffoot_imag',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_link1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_link2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_link3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_link4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_link5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_link6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_link7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
