# Generated by Django 4.1.1 on 2022-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0025_aboutus_copy_aboutus_ffoot_imag_aboutus_qui_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='ffoot_imag1',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='ffoot_imag2',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='ffoot_imag3',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='ffoot_imag4',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='qui_links',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
