# Generated by Django 4.1.1 on 2022-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0026_aboutus_ffoot_imag1_aboutus_ffoot_imag2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='qui_links',
            field=models.ImageField(default='exit', upload_to='thumnail/'),
            preserve_default=False,
        ),
    ]
