# Generated by Django 4.1.1 on 2022-09-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0027_alter_aboutus_qui_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='cou_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cou_link1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cou_link2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cou_link3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cou_link4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cou_link5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
