# Generated by Django 4.1.1 on 2022-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0028_aboutus_cou_link_aboutus_cou_link1_aboutus_cou_link2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
