# Generated by Django 4.1.1 on 2022-09-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0030_aboutus_nav_link_aboutus_nav_link1_aboutus_nav_link2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
